### ISSUE TITLE
NumericUpDown Culture problem

### ISSUE THREAD

**Issue by fredericoregateiro** [MahApps/MahApps.Metro#2149]
Hello,

I'm using the NumericUpDown control in a app with the culture pt-PT, in this culture the decimal point is ',' and using a numeric key pad the decimal key is ignored.

When the user press the decimal key, even when the decimal point is not the dot, the text entered should be the given culture decimal separator, like System.Globalization.CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator.

Is any way to do this, or is this a limitation of the current control.

I've tested with the 1.1.2 and 1.1.3-ALPHA174 versions, in the MetroDemo.NET45 project.

Thanks,
Frederico

**Comment by punker76** [comment]
@fredericoregateiro it seems you must set the Culture explicit https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/NumericUpDown.cs#L294
cause NumericUpDown uses `Language.GetSpecificCulture();` by default https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/NumericUpDown.cs#L442
NumericUpDown check and use `NumberDecimalSeparator` already 
https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/NumericUpDown.cs#L651

**Comment by fredericoregateiro** [comment]
@punker76 i have the culture set on the control also
Culture="pt-PT"
With this culture, the decimal point on my keypad doesn't work, only the comma on the qwerty keyboard sets the decimal point correctly. The decimal key works only with the culture set like "en-US" or similar.

Using the pt-PT culture, the users expect that the decimal point on the keypads set the comma ',' and start to fill the decimal places.

Thanks,
Frederico

**Comment by punker76** [comment]
@fredericoregateiro how is your os keyboard configured?

**Comment by fredericoregateiro** [comment]
Is this picture enough?

![settings](https://cloud.githubusercontent.com/assets/6304701/10540914/75173296-7404-11e5-9776-cadcf67da561.jpg)

The keypad i'm using is the numeric keypad, the most used to enter numeric values. Like this one:

![asus_n550_15](https://cloud.githubusercontent.com/assets/6304701/10540993/52188938-7405-11e5-950f-5b65a19523c3.jpg)

**Comment by punker76** [comment]
question is, what comes in `OnPreviewTextInput` if you hit the numeric delete key?

```csharp
        protected void OnPreviewTextInput(object sender, TextCompositionEventArgs e)
        {
            e.Handled = true;
            if (string.IsNullOrWhiteSpace(e.Text) ||
                e.Text.Length != 1)
            {
                return;
            }

            string text = e.Text;

            if (char.IsDigit(text[0]))
            {
                e.Handled = false;
            }
            else
            {
                CultureInfo equivalentCulture = SpecificCultureInfo;
                NumberFormatInfo numberFormatInfo = equivalentCulture.NumberFormat;
                TextBox textBox = (TextBox)sender;
                bool allTextSelected = textBox.SelectedText == textBox.Text;

                if (numberFormatInfo.NumberDecimalSeparator == text)
                {
```

**Comment by fredericoregateiro** [comment]
Pressing the decimal key on the keyboard:
e.Text: "."
numberFormatInfo.NumberDecimalSeparator: ","

On the OnTextBoxKeyDown event the keypad decimal key returns: e.Key: Decimal System.Windows.Input.Key
and the period key on the normal keyboard returns: e.Key: OemPeriod System.Windows.Input.Key

I've used the MahApps sample app to test this, and set the culture to portuguese:

![mahapps_test](https://cloud.githubusercontent.com/assets/6304701/10543231/2bdd1a58-7415-11e5-8e0f-4ab8f5e36f0a.png)

**Comment by punker76** [comment]
>Pressing the decimal key on the keyboard: e.Text: "."

So how do we should solve this? Cause this is what the TextBox us give.

**Comment by punker76** [comment]
@fredericoregateiro but maybe this one could the answer: http://stackoverflow.com/a/3879284/920384

```csharp
public partial class App : Application
{
    static App()
    {
        FrameworkElement.LanguageProperty.OverrideMetadata(
            typeof(FrameworkElement),
            new FrameworkPropertyMetadata(
                XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));
    }
}
```

**Comment by punker76** [comment]
@fredericoregateiro if i do this, then it works for me ™

```csharp
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo("pt-PT");
            FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement),
                                                               new FrameworkPropertyMetadata(
                                                                   XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));
            base.OnStartup(e);
        }
    }
```

**Comment by fredericoregateiro** [comment]
Strange, i still get the same result, the e.Text="." and the numberFormatInfo.NumberDecimalSeparator=","

I would suggest that the "." could be treated like the decimalSeparator all the time, and so the comma or the decimal key would give the same result, start to edit the decimal part of the number.
Or some property that allow us to give the decimal key this behavior, even if the numberFormatInfo.NumberDecimalSeparator is not the "."

**Comment by punker76** [comment]
@fredericoregateiro maybe you must set the CurrentUICulture too. I think this is not MahApps related stuff here and I don't want any other hack in the control.

**Comment by fredericoregateiro** [comment]
Yes, i really don't like hacks too :smile:

Setting the CurrentUICulture don't fix this.
And given the decimal key the behavior of the decimal point, i don't think it's a hack.

Fot example, on the devexpress control
https://demos.devexpress.com/MVCxDataEditorsDemos/Editors/SpinEdit
pressing de decimal key or the comma on the keyboard, gives the same result, starts to edit the decimal digits of the number.

**Comment by fredericoregateiro** [comment]
Another example is the windows calculator, the decimal key or the comma key is allways translated to the NumberDecimalSeparator, "," in my case.
One example of handling the decimal separator: 
https://www.devexpress.com/Support/Center/Question/Details/Q94237

**Comment by fredericoregateiro** [comment]
So, i've been testing the changes that i was talking before, and the change should be done in the OnTextBoxKeyDown

```c#
private void OnTextBoxKeyDown(object sender, KeyEventArgs e)
{
    _manualChange = true;

    if (e.Key == Key.Decimal || e.Key == Key.OemPeriod)
    {
        TextBox textBox = sender as TextBox;

        if (this.Culture != null)
        {
            if (textBox.Text.Contains(this.Culture.NumberFormat.NumberDecimalSeparator) == false)
            {
                //the control doesn't contai the decimal separator
                //so we get the current caret index to insert the current culture decimal separator
                var caret = textBox.CaretIndex;
                //update the control text
                textBox.Text = textBox.Text.Insert(caret, this.Culture.NumberFormat.CurrencyDecimalSeparator);
                //move the caret to the correct position
                textBox.CaretIndex = caret + 1;
            }
            e.Handled = true;
        }
    }
}
```
@punker76 do you think this should integrate the control code?
