### ISSUE TITLE
Windows does not show GlowBrush on Resize="NoResize"

### ISSUE THREAD

**Issue by evilbaschdi** [MahApps/MahApps.Metro#3471]
**Describe the bug**
I recently figured out that my about windows does not have a glow effect. I took a look inside the code and played around with it a little bit. Since I switched to Resize="CanMinimize" the glow effect is back and running.

**Screenshots**
![image](https://user-images.githubusercontent.com/1897807/54146117-9413fb80-442f-11e9-9ecc-3e796756d38a.png)

![image](https://user-images.githubusercontent.com/1897807/54146229-cde50200-442f-11e9-992e-754df1ba521c.png)

**Environment(please complete the following information):**
 - MahApps.Metro version 2.0.0-alpha026*
 - OS: Win10 1809
 - Visual Studio 2017, 2019
 - .NET Framework 4.5 - 4.8 + dotnet core 3

**Repo**
https://github.com/evilbaschdi/EvilBaschdi.CoreExtended/blob/develop/EvilBaschdi.CoreExtended/Mvvm/View/AboutWindow.xaml

**Additional context**

**Comment by punker76** [comment]
@evilbaschdi Do you have a branch with the latest changes to the MahApps.Metro alpha version? The current develop of your repo is for v1.6.5. Thx

**Comment by evilbaschdi** [comment]
what exactly do you mean? "develop" is referencing 2.0.0-alpha0262.

**Comment by punker76** [comment]
@evilbaschdi My fault, I didn't update the source 🙈

**Comment by punker76** [comment]
@evilbaschdi Seems like it's fixed with latest ControlzEx v4.0.0-alpha0249 (from appveyor). I compiled your source as Release and doesn't see this issue (only as Debug with attached VS debugger it can be that the glow is showing a little bit late)

**Comment by evilbaschdi** [comment]
I know about the delay, yes. Current code ResizeMode set to "CanMinimize". If you switch to "NoResize" you might see the issue. Otherwise I'll try the ControlzEx update once it is released.

**Comment by punker76** [comment]
@evilbaschdi Got it

**Comment by HispidaBytes** [comment]
Hi, the issue is still present.

Tested with:
- MahApps.Metro version 2.3.3
- OS: Win10 2004
- Visual Studio 2019
- .NET Core 3.1

Link to a repo I've created to show the issue:
https://github.com/HispidaBytes/MahApps_GlowBrushIssue

**Comment by punker76** [comment]
> Hi, the issue is still present.
> 
> Tested with:
> 
> * MahApps.Metro version 2.3.3
> * OS: Win10 2004
> * Visual Studio 2019
> * .NET Core 3.1
> 
> Link to a repo I've created to show the issue:
> https://github.com/HispidaBytes/MahApps_GlowBrushIssue

@HispidaBytes Thx for reporting, I’ll look for this.
